Добавил сервисы для Item и User
Programmer112P/java-shareit pull request #1
Opened 2023-06-07 07:26 UTC by Programmer112P

2023-06-08 08:20 UTC, YazykovMikhail requested changes

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private ItemRequest request;
не торопись, в этом задании это не нужно

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/FakeItemRepository.java
> +public class FakeItemRepository {
Fake - ну не лучшее название)
Embedded

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/FakeItemRepository.java
> +        itemToCreate.setId(idGenerator++);
++idGenerator
Каждый менто должен отвечать за свои данные, а ты в методе увелиичваешь id для селдующего использования
И соотвественно private long idGenerator = 0;

поправь везде

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/FakeItemRepository.java
> +    public Item update(Long itemId, Item itemToUpdate) {
public Item update(Item itemToUpdate) - сигнатуту метода чуть поменяй, только сам обьект приходит. id уже в обьекте должно быть

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final DtoToItemMapper dtoToItemMapper;
Мапер доледн быть один, протсо там буду тдва метода 
itemToDto
dtoToItem

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public Item update(final Item newItem, final Long itemId, final Long userId) {
id итема уже передается в самом обьекте, его не нужно передавать отдельно. 

вот более простой пример:
@Override
	public ItemDto updateItem(long userId, ItemDto itemDto) {
		Item item = itemRepository.findById(itemDto.getId());
		if (item == null || item.getOwner().getId() != userId) {
			throw new NotFoundException("Item with id=" + itemDto.getId() + " not found");
		}
		if (itemDto.getName() != null) {
			item.setName(itemDto.getName());
		}
		if (itemDto.getDescription() != null) {
			item.setDescription(itemDto.getDescription());
		}
		if (itemDto.getAvailable() != null) {
			item.setAvailable(itemDto.getAvailable());
		}

		itemRepository.update(item);
		return ItemMapper.toItemDto(item);
	}
	
маппинг можно делать как и в сервисе, так и на стороне контроллеров. Это зависит от проекта. Оставляй как тебе более удобно. Но вообще скорее маппинг лучше делать на уровне сервиса, потому что в сервисе могут быть еще много промежутных вызовов ддругих сервисов и мапперы все равно будут вызываться из сервиса

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (!text.isBlank()) {
если text = null
то будет null.isBlank() -> NPE
```
if (text == null || text.isBlank()) {
			return Collections.emptyList();
		}
```
		
а дальше уже код с логикой

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        log.info("ItemService update: выполнен запрос на обновление вещи с id {}", itemId);
Такие лог дублируют логи из контроллера, в нем нет смысла. при переходе из сервиса в контрллер ничего не поменяется , булет просто два одинаковых лога, тут можно убрать

поправь такое везде

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        log.info("ItemService update: запрос на обновление вещи с id {}", itemId);
Такие лог дублируют логи из контроллера, в нем нет смысла. при переходе контролера в сервис ничего не поменяется , будет просто два одинаковых лога, тут можно бурать

поправь такое везде

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/mapper/ItemToDtoMapper.java
> +@Mapper(componentModel = "spring")
Хорошее решение, только сделай один класс
ItemMapper и там все методы для маппинга в обде стороны

Такое же замечание для User

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    public User update(final User newUser, final Long userId) {
```
@Override
	public UserDto updateUser(UserDto userDto) {
		final User newUser = UserMapper.toUser(userDto);

		final User user = userRepository.findById(newUser.getId());
		if (user == null) {
			throw new NotFoundException("User with id=" + newUser.getId() + " not found");
		}

		if (newUser.getName() == null) {
			newUser.setName(user.getName());
		}
		if (newUser.getEmail() == null) {
			newUser.setEmail(user.getEmail());
		}
		userRepository.update(newUser);
		return UserMapper.toUserDto(newUser);
	}
```

Все попроще

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/FakeUserRepository.java
> +    public User update(User userToUpdate, Long userId) {
Можно хранить сделать поле
	private final Set<String> emailUniqSet = new HashSet<>();
для проверки уникальности емейлов
И тогда при обновлении проверять 

```
public void update(User user) {
		final String email = user.getEmail();
		storage.computeIfPresent(user.getId(), (id, u) -> {
					if (!email.equals(u.getEmail())) {
						if (emailUniqSet.contains(email)) {
							throw new DataAlreadyExistException("Email: " + email + " already exists");
						}
						emailUniqSet.remove(u.getEmail());
						emailUniqSet.add(email);
					}
					return user;
				}
		);
	}
```

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/FakeUserRepository.java
> +    public Optional<User> create(User userToCreate) {
соотвесвенно и при создании проверять:
на имейл, который хранится в отдельном поле 
	private final Set<String> emailUniqSet = new HashSet<>();

```
public User save(User user) {
		final String email = user.getEmail();
		if (emailUniqSet.contains(email)) {
			throw new DataAlreadyExistException("Email: " + email + " already exists");
		}
		user.setId(++counter);
		storage.put(user.getId(), user);
		emailUniqSet.add(email);
		return user;
	}
```

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/FakeUserRepository.java
> +    public Optional<User> delete(Long userId) {
delete обвчно void
Это мапа позволяет вернуть удаленный обьект, с БД не так просто

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private boolean validateEmail(String email, Long userId) {
Да, для этого в репозитории создать 
	private final Set<String> emailUniqSet = new HashSet<>();

я описал это в репозитории. 
Так что этот методбудет не нужен.

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +     * то чужой репозиторий просто будет недоступен, так как это будут 2 отдельных приложения
Проверять не обязательно что такой пользователь сущетсвует. 
Потому что в бд у итема есть id пользователя. 
Если пользователь будет удален, то и все его итемы будут удалены.
Поэтому просто по id пользователя получаем все итемы, если такого пользователя нет, то и итемов не будет

2023-06-08 08:20 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +     * Если у меня будет manyToOne связь, можно ли ещё хранить в Item просто OwnerId для сохранения в БД
Ну тут ходить в бд нужно будет в любом случае, что бы проверить что такой пользователь есть.
отдельно хранить userId не нужно, у тебя есть поле owner там уже будет id. 
при обновлении итемов пользователи не будет затрагиваться.

2023-06-08 15:11 UTC, Programmer112P commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public Item update(final Item newItem, final Long itemId, final Long userId) {
Я долго разбирался с этим, и так не нашел правильного решения
А если в каком-то месте нужна будет доменная модель целиком, а не только те поля, что в DTO наружу отдаются, тогда как? Например для другого сервиса, который что-то считает исходя из всех полей модели
DTO это ведь как бы уже работа с представлением, и оно может быть разным даже для одного и того же сервиса
Поэтому я все-таки решил оставлять в контроллере

2023-06-08 15:39 UTC, Programmer112P commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        log.info("ItemService update: выполнен запрос на обновление вещи с id {}", itemId);
Вот тут тоже вопрос
Я все слои делал максимально независимыми друг от друга, чтобы у меня сервисный слой был самодостаточным от контроллеров и БД.
Соответственно, и логирование на каждый слой у меня своё
Если, например, с моим сервисом будут общаться не через контроллеры, то у меня в логах вообще ничего не будет
Поэтому я дублировал логи на каждом слое

2023-06-08 19:50 UTC, Programmer112P commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +     * то чужой репозиторий просто будет недоступен, так как это будут 2 отдельных приложения
Мне не нравится возвращать просто пустой список, если пользователя не существует 
У нас где-то в логике программы есть ошибка, а возвращается 200

2023-06-09 08:13 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +     * то чужой репозиторий просто будет недоступен, так как это будут 2 отдельных приложения
В 99 процентах случаях ты пользователь будет и тогда ты делаешь 2 запроса в БД, всмето одного. 
Тут многое зависит от бизнес задачи, можно и так и так

2023-06-09 08:16 UTC, YazykovMikhail approved these changes

2023-06-09 08:16 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +     * Вопрос по контроллерам - что лучше возвращать - ResponseEntity или просто Dto?
Лучше ResponseEntity

2023-06-09 08:16 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    //Возвращать что-нибудь при удалении?
Вот так возвращают, если возвращать ResponseEntity
ResponseEntity<Void>

и что бы это вернуть делают вот так 
        return ResponseEntity.ok().build();

2023-07-06 14:56 UTC, merged